logging:
  config: classpath:logback.xml
server:
  port: 8100
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:////todo
    name: root
    password: yxd729844
  thymeleaf:
    mode: LEGACYHTML5
  jmx:
    enabled: false
application:
  info:
    name: jtodo
    description: "A simple application for managing user's todo-list based on Java"
    server: http://jtodo.wandan.site
    static: http://jtodo.wandan.site/static
  security:
    social:
      filter-processes-url: /user/auth
      passport:
        provider-id: passport
        app-id: xxx
        app-secret: xxx
      github:
        provider-id: github
        app-id: b8815440e7e47e1c5c91
        app-secret: 3c899e8dcb51e6654ea3379fbdb0dc9e33b36382
      we-chat:
        provider-id: wechat
        app-id: wx75156c2091b6e70e
        app-secret: 1bd81dee2043403988db1ca1fe949b8e